/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.3.v201507280808.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef COMMONAPI_Calculator_STUB_HPP_
#define COMMONAPI_Calculator_STUB_HPP_

#include <functional>




#include <v1_0/commonapi/Calculator.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <vector>

#include <CommonAPI/Stub.hpp>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1_0 {
namespace commonapi {

/**
 * Receives messages from remote and handles all dispatching of deserialized calls
 * to a stub for the service Calculator. Also provides means to send broadcasts
 * and attribute-changed-notifications of observable attributes as defined by this service.
 * An application developer should not need to bother with this class.
 */
class CalculatorStubAdapter
    : virtual public CommonAPI::StubAdapter, 
      public Calculator {
 public:



    virtual void deactivateManagedInstances() = 0;
protected:
    /**
     * Defines properties for storing the ClientIds of clients / proxies that have
     * subscribed to the selective broadcasts
     */
};

/**
 * Defines the necessary callbacks to handle remote set events related to the attributes
 * defined in the IDL description for Calculator.
 * For each attribute two callbacks are defined:
 * - a verification callback that allows to verify the requested value and to prevent setting
 *   e.g. an invalid value ("onRemoteSet<AttributeName>").
 * - an action callback to do local work after the attribute value has been changed
 *   ("onRemote<AttributeName>Changed").
 *
 * This class and the one below are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class CalculatorStubRemoteEvent
{
public:
    virtual ~CalculatorStubRemoteEvent() { }

};

/**
 * Defines the interface that must be implemented by any class that should provide
 * the service Calculator to remote clients.
 * This class and the one above are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class CalculatorStub
    : public virtual CommonAPI::Stub<CalculatorStubAdapter, CalculatorStubRemoteEvent>
{
public:
    typedef std::function<void (double _result)>addReply_t;
    typedef std::function<void (double _result)>subtarctReply_t;
    typedef std::function<void (double _result)>multiplyReply_t;
    typedef std::function<void (double _qoutient, int64_t _remainder)>divideReply_t;
    typedef std::function<void (int64_t _remainder)>modReply_t;
    typedef std::function<void (double _result)>sqrtReply_t;
    typedef std::function<void (double _result)>cubertReply_t;
    typedef std::function<void (double _result)>exponReply_t;

    virtual ~CalculatorStub() {}
    virtual const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> clientId) = 0;


    /// This is the method that will be called on remote calls on the method add.
    virtual void add(const std::shared_ptr<CommonAPI::ClientId> _client, double _operand1, double _operand2, addReply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method subtarct.
    virtual void subtarct(const std::shared_ptr<CommonAPI::ClientId> _client, double _operand1, double _operand2, subtarctReply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method multiply.
    virtual void multiply(const std::shared_ptr<CommonAPI::ClientId> _client, double _operand1, double _operand2, multiplyReply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method divide.
    virtual void divide(const std::shared_ptr<CommonAPI::ClientId> _client, double _dividend, double _divisor, divideReply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method mod.
    virtual void mod(const std::shared_ptr<CommonAPI::ClientId> _client, int64_t _dividend, int64_t _divisor, modReply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method sqrt.
    virtual void sqrt(const std::shared_ptr<CommonAPI::ClientId> _client, double _operand, sqrtReply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method cubert.
    virtual void cubert(const std::shared_ptr<CommonAPI::ClientId> _client, double _operand, cubertReply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method expon.
    virtual void expon(const std::shared_ptr<CommonAPI::ClientId> _client, double _base, double _exponent, exponReply_t _reply) = 0;

    using CommonAPI::Stub<CalculatorStubAdapter, CalculatorStubRemoteEvent>::initStubAdapter;
    typedef CommonAPI::Stub<CalculatorStubAdapter, CalculatorStubRemoteEvent>::StubAdapterType StubAdapterType;
    typedef CommonAPI::Stub<CalculatorStubAdapter, CalculatorStubRemoteEvent>::RemoteEventHandlerType RemoteEventHandlerType;
    typedef CalculatorStubRemoteEvent RemoteEventType;
    typedef Calculator StubInterface;
};

} // namespace commonapi
} // namespace v1_0

#endif // COMMONAPI_Calculator_STUB_HPP_
